COMP: TransformIO: TransformFile(Reader|Writer) still need to be exported.
This commit partially reverts commit 88eeafa (COMP: TransformIO: Fix VS
build errors removing extra EXPORT ) to ensure symbols and fix the following
link error:

  [100%] Linking CXX executable ../../../../bin/ITKIOTransformBaseTestDriver
  CMakeFiles/ITKIOTransformBaseTestDriver.dir/itkTransformFileWriterTest.cxx.o: In function `itkTransformFileWriterTest(int, char**)':
  /path/to/Modules/IO/TransformBase/test/itkTransformFileWriterTest.cxx:34: undefined reference to `itk::TransformFileWriterTemplate<double>::New()'
  /path/to/Modules/IO/TransformBase/test/itkTransformFileWriterTest.cxx:45: undefined reference to `itk::TransformFileWriterTemplate<double>::Update()'
  /path/to/Modules/IO/TransformBase/test/itkTransformFileWriterTest.cxx:56: undefined reference to `itk::TransformFileWriterTemplate<double>::Update()'

See #3393

Change-Id: I0715aa69479853062212298b35f490dead4c7ab6